-- Conztanz SBR_MESSAGE table creation
CREATE TABLE ${persistence.schema.name}.SBR_MESSAGE
(
   ID SERIAL NOT NULL,
   VERSION SMALLINT NOT NULL,
   CREATE_TIMESTAMP_DB TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   UPDATE_TIMESTAMP_DB TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   UUID_DB UUID,
   
   SEQUENCE_NUMBER INTEGER NOT NULL,

   CONSTRAINT "SBR_MESSAGE.PRIMARY_KEY"   PRIMARY KEY (ID),
   CONSTRAINT "SBR_MESSAGE.UNIQUE_UUID"   UNIQUE (UUID_DB)
)
WITH
(
  OIDS = FALSE
);

ALTER TABLE ${persistence.schema.name}.SBR_MESSAGE OWNER TO ${persistence.db.admin.name};
