-- Conztanz SIMPLE_ENTITY table downgrade
ALTER TABLE ${persistence.schema.name}.SIMPLE_ENTITY RENAME COLUMN CREATE_TIMESTAMP_DB TO CREATE_TIMESTAMP; 
ALTER TABLE ${persistence.schema.name}.SIMPLE_ENTITY RENAME COLUMN UPDATE_TIMESTAMP_DB TO UPDATE_TIMESTAMP;