-- Conztanz SIMPLE_ENTITY table upgrade
ALTER TABLE ${persistence.schema.name}.SIMPLE_ENTITY RENAME COLUMN CREATE_TIMESTAMP TO CREATE_TIMESTAMP_DB; 
ALTER TABLE ${persistence.schema.name}.SIMPLE_ENTITY RENAME COLUMN UPDATE_TIMESTAMP TO UPDATE_TIMESTAMP_DB;