-- Conztanz SIMPLE_ENTITY table creation
CREATE TABLE ${persistence.schema.name}.SIMPLE_SEQUENCED_WORKING_MESSAGE
(
   ID SERIAL NOT NULL,
   VERSION SMALLINT NOT NULL,
   CREATE_TIMESTAMP_DB TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   UPDATE_TIMESTAMP_DB TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   UUID_DB UUID,

   SEQUENCE_NUMBER smallint,
   OBJECT_ID VARCHAR(15),



   CONSTRAINT "SIMPLE_SEQUENCED_WORKING_MESSAGE.PRIMARY_KEY" PRIMARY KEY (ID),
   CONSTRAINT "SIMPLE_SEQUENCED_WORKING_MESSAGE.UNIQUE_UUID" UNIQUE (UUID_DB)
)
WITH
(
  OIDS = FALSE
);
ALTER TABLE ${persistence.schema.name}.SIMPLE_SEQUENCED_WORKING_MESSAGE OWNER TO ${persistence.db.admin.name};
