-- Conztanz SIMPLE_ENTITY table creation
CREATE TABLE ${persistence.schema.name}.SIMPLE_SEQUENCED_WAITING_MESSAGE
(
   ID SERIAL NOT NULL, 
   VERSION SMALLINT NOT NULL, 
   CREATE_TIMESTAMP_DB TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   UPDATE_TIMESTAMP_DB TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   UUID_DB UUID,
   
   --MESSAGE_VERSION VARCHAR(10) NOT NULL,

   SEQUENCE_NUMBER smallint,
   OBJECT_ID VARCHAR(50) NOT NULL,
   RAW_PAYLOAD bytea NOT NULL,
   TRANSFORMED_PAYLOAD TEXT,
   STATUS VARCHAR(10),


   
   
   CONSTRAINT "SIMPLE_SEQUENCED_WAITING_MESSAGE.PRIMARY_KEY" PRIMARY KEY (ID),
   CONSTRAINT "SIMPLE_SEQUENCED_WAITING_MESSAGE.UNIQUE_UUID" UNIQUE (UUID_DB)
)
WITH
(
  OIDS = FALSE
);

ALTER TABLE ${persistence.schema.name}.SIMPLE_SEQUENCED_WAITING_MESSAGE OWNER TO ${persistence.db.admin.name};
